// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm2YWperozEffTtZLqu7S9-TFslcVtUk8',
    appId: '1:666389126015:web:bc23a656b9510b50ab184a',
    messagingSenderId: '666389126015',
    projectId: 'kofi-multi-store',
    authDomain: 'kofi-multi-store.firebaseapp.com',
    storageBucket: 'kofi-multi-store.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzwvDCXyijAlR0m8Q4i96HqP0EkmGuFjo',
    appId: '1:666389126015:android:c2fc6a2254b45333ab184a',
    messagingSenderId: '666389126015',
    projectId: 'kofi-multi-store',
    storageBucket: 'kofi-multi-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhf6aUiTXh4_oHOD1vYEKn-QED-__3jbY',
    appId: '1:666389126015:ios:fc71797cec3f8669ab184a',
    messagingSenderId: '666389126015',
    projectId: 'kofi-multi-store',
    storageBucket: 'kofi-multi-store.appspot.com',
    iosClientId: '666389126015-n4hmm6t9096ueq311qcnjvbnvsmmjdga.apps.googleusercontent.com',
    iosBundleId: 'com.example.kofiMultiStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhf6aUiTXh4_oHOD1vYEKn-QED-__3jbY',
    appId: '1:666389126015:ios:fc71797cec3f8669ab184a',
    messagingSenderId: '666389126015',
    projectId: 'kofi-multi-store',
    storageBucket: 'kofi-multi-store.appspot.com',
    iosClientId: '666389126015-n4hmm6t9096ueq311qcnjvbnvsmmjdga.apps.googleusercontent.com',
    iosBundleId: 'com.example.kofiMultiStore',
  );
}
